# .github/workflows/ci-cd.yml
name: CI/CD Test Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate Deployment/Test
        run: echo "🚀 CI/CD test passed after push to main"
